name: BlocksHub-LogBlock
main: org.PrimeSoft.blocksHub.logBlock.BlocksHubPlugin
version: 1.0
website: https://github.com/SBPrime/BlocksHub/
description: HawkEye blocks hub implementation.
authors: [SBPrime]
depend: [BlocksHub, LogBlock]
softdepend: []
commands:
permissions:
