name: BlocksHub-GriefPrevention-8x
main: org.PrimeSoft.blocksHub.griefPrevention8x.BlocksHubPlugin
version: 1.2
website: https://github.com/SBPrime/BlocksHub/
description: GriefPrevention blocks hub implementation.
authors: [SBPrime]
depend: [BlocksHub, GriefPrevention]
softdepend: []
commands:
permissions:
