name: BlocksHub-CoreProtect
main: org.PrimeSoft.blocksHub.coreProtect.BlocksHubPlugin
version: 1.2
website: https://github.com/SBPrime/BlocksHub/
description: CoreProtect blocks hub implementation.
authors: [SBPrime]
depend: [BlocksHub, CoreProtect]
softdepend: []
commands:
permissions:
