name: BlocksHub-Factions
main: org.PrimeSoft.blocksHub.factions.FactionsPlugin
version: 1.2
website: https://github.com/SBPrime/BlocksHub/
description: Factions blocks hub implementation.
authors: [SBPrime]
depend: [BlocksHub, Factions, MassiveCore]
softdepend: []
commands:
permissions:
