name: BlocksHub
main: org.primesoft.blockshub.BlocksHub
version: 2
website: https://github.com/SBPrime/BlocksHub/
description: Logger & Block access API.
authors: [SBPrime]
depend: []
softdepend: []
commands:
  bh:
    description: 'Displays the help for BlocksHub.'
    usage: /<command>
    aliases: BlocksHub
permissions:
  BlocksHub.admin.state:
    default: op
    description: Allows to view plugin status.
  BlocksHub.admin.reload:
    default: op
    description: Allows the configuration reload.