name: BlocksHub
main: org.PrimeSoft.blocksHub.BlocksHub
version: 0.4
website: http://dev.bukkit.org/bukkit-plugins/blockshub/
description: Logger & Block access API.
authors: [SBPrime]
depend: []
softdepend: [CoreProtect, LogBlock, Prism, HawkEye, WorldGuard, Residence, GriefPrevention]
commands:
  bh:
    description: 'Displays the help for BlocksHub.'
    usage: /<command>
    aliases: BlocksHub
permissions:
  BlocksHub.admin.state:
    default: op
    description: Allows to view plugin status.
  BlocksHub.admin.reload:
    default: op
    description: Allows the configuration reload.