name: BlocksHub-WorldGuard
main: org.PrimeSoft.blocksHub.worldGuard.BlocksHubPlugin
version: 1.1
website: https://github.com/SBPrime/BlocksHub/
description: WorldGuard blocks hub implementation.
authors: [SBPrime]
depend: [BlocksHub, WorldGuard]
softdepend: []
commands:
permissions:
