name: BlocksHub-HawkEye
main: org.PrimeSoft.blocksHub.hawkEye.BlocksHubPlugin
version: 1.2
website: https://github.com/SBPrime/BlocksHub/
description: HawkEye blocks hub implementation.
authors: [SBPrime]
depend: [BlocksHub, HawkEye]
softdepend: []
commands:
permissions:
