name: BlocksHub-Residence
main: org.PrimeSoft.blocksHub.residence.BlocksHubPlugin
version: 1.1
website: https://github.com/SBPrime/BlocksHub/
description: Residence blocks hub implementation.
authors: [SBPrime]
depend: [BlocksHub, Residence]
softdepend: []
commands:
permissions:
