name: BlocksHub-GriefPrevention-7x
main: org.PrimeSoft.blocksHub.BlocksHubPlugin
version: 1.0
website: https://github.com/SBPrime/BlocksHub/
description: GriefPrevention blocks hub implementation.
authors: [SBPrime]
depend: [BlocksHub, GriefPrevention]
softdepend: []
commands:
permissions:
